INSERT INTO category(id, name) VALUES (1, 'MEAT');
INSERT INTO category(id, name) VALUES (2, 'FISH');
INSERT INTO category(id, name) VALUES (3, 'VEGETABLES');
INSERT INTO category(id, name) VALUES (4, 'SAUCES');

INSERT INTO ingredient(id, name, price, idcategory) VALUES (1, 'Bacon', 1, 1);
INSERT INTO ingredient(id, name, price, idcategory) VALUES (2, 'Salami', 1, 1);
INSERT INTO ingredient(id, name, price, idcategory) VALUES (3, 'Ham', 1, 1);
INSERT INTO ingredient(id, name, price, idcategory) VALUES (4, 'Minced Meat', 1, 1);
INSERT INTO ingredient(id, name, price, idcategory) VALUES (5, 'Chicken Strips', 1, 1);
INSERT INTO ingredient(id, name, price, idcategory) VALUES (6, 'Tuna', 1, 2);
INSERT INTO ingredient(id, name, price, idcategory) VALUES (7, 'Crab', 1, 2);
INSERT INTO ingredient(id, name, price, idcategory) VALUES (8, 'Anchovies', 1, 2);
INSERT INTO ingredient(id, name, price, idcategory) VALUES (9, 'Pineapple', 1, 3);
INSERT INTO ingredient(id, name, price, idcategory) VALUES (10, 'Spinat', 1, 3);
INSERT INTO ingredient(id, name, price, idcategory) VALUES (11, 'Paprika', 1, 3);
INSERT INTO ingredient(id, name, price, idcategory) VALUES (12, 'Mushrooms', 1, 3);
INSERT INTO ingredient(id, name, price, idcategory) VALUES (13, 'Olives', 1, 3);
INSERT INTO ingredient(id, name, price, idcategory) VALUES (14, 'Egg', 1, 3);
INSERT INTO ingredient(id, name, price, idcategory) VALUES (15, 'Onions', 1, 3);
INSERT INTO ingredient(id, name, price, idcategory) VALUES (16, 'Broccoli', 1, 3);
INSERT INTO ingredient(id, name, price, idcategory) VALUES (17, 'Onions', 1, 3);
INSERT INTO ingredient(id, name, price, idcategory) VALUES (18, 'Artichokes', 1, 3);
INSERT INTO ingredient(id, name, price, idcategory) VALUES (19, 'Pepperoni', 1, 3);
INSERT INTO ingredient(id, name, price, idcategory) VALUES (20, 'Mozzarella', 1, 3);
INSERT INTO ingredient(id, name, price, idcategory) VALUES (21, 'Pepperoni', 1, 3);
INSERT INTO ingredient(id, name, price, idcategory) VALUES (22, 'Corn', 1, 3);
INSERT INTO ingredient(id, name, price, idcategory) VALUES (23, 'Chili Peppers', 1, 3);
INSERT INTO ingredient(id, name, price, idcategory) VALUES (24, 'Gorgonzola', 1, 3);
INSERT INTO ingredient(id, name, price, idcategory) VALUES (25, 'Garlic', 1, 3);
INSERT INTO ingredient(id, name, price, idcategory) VALUES (26, 'Tomatoes', 1, 3);
INSERT INTO ingredient(id, name, price, idcategory) VALUES (27, 'Crème Fraiche', 0.50, 4);
INSERT INTO ingredient(id, name, price, idcategory) VALUES (28, 'Barbeceau Sauce', 0.50, 4);
INSERT INTO ingredient(id, name, price, idcategory) VALUES (29, 'Spinach', 1, 3);
INSERT INTO ingredient(id, name, price, idcategory) VALUES (30, 'Curry Sauce', 0.50, 4);
INSERT INTO ingredient(id, name, price, idcategory) VALUES (31, 'Scampi', 1, 2);
INSERT INTO ingredient(id, name, price, idcategory) VALUES (32, 'Sauce Hollandaise', 0.50, 4);